name: Godot Export

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [Windows, Linux]
        ext: [exe, x86_64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: sharkwouter/setup-godot@v1
        with:
          godot-version: 4.2.1
          use-dotnet: false

      - name: Export game
        run: |
          mkdir -p build/${{ matrix.preset }}
          godot --headless --export-release "${{ matrix.preset }}" "build/${{ matrix.preset }}/Shrine.${{ matrix.ext }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.preset }}
          path: build/${{ matrix.preset }}
