name: Godot Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    name: Export ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [windows, linux]
        include:
          - target: windows
            os: windows-latest
            preset: Windows
            ext: .exe
          - target: linux
            os: ubuntu-latest
            preset: Linux
            ext: .x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Godot
      uses: firebelley/setup-godot@v1
      with:
        version: 4.2.1      # プロジェクト Godot バージョンに合わせて!
        use-godot: true      # `godot` コマンドを PATH に追加

    - name: Export (headless)
      run: |
        mkdir -p build/${{ matrix.target }}
        godot -q --headless \
          --export-release "${{ matrix.preset }}" \
          "build/${{ matrix.target }}/Shrine${{ matrix.ext }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.target }}
        path: build/${{ matrix.target }}
